import { GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { Col, Container, Row } from 'react-grid-system'
import IProductDTO from 'interfaces/IProductDTO'
import { api } from 'service/api'
import styles from 'styles/Index.module.scss'
import Imagem from "/public/Frame.png"

export const clickItem = async (idProduct: number): Promise<void> => {
  const { data } = await api.post<{ click: number }>('/clickCounter', { idProduct })
  console.log(data.click)
}

export const Teste = async () => {
  const { data } = await api.get('/Item/allItems')
  return data
}

export default function Home({ itens }: { itens: IProductDTO[] }) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {itens?.map((item: IProductDTO) => (
          <Link key={item?.id} href={`/${item?.id}`}>
            <div onClick={() => clickItem(item?.id)} className={styles.teste}>
              <div>
                <h3>{item?.name}</h3>
                <h4>{item?.description}</h4>
                <h2>R$ {item?.price}</h2>
              </div>
              <div>
                <Image
                  alt="The guitarist in the concert."
                  src={Imagem}
                  width={100}
                  height={100}
                />
              </div>
            </div>
          </Link>
        ))}
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
// export const getStaticProps = async () => {
  const { data } = await api.get('/Item/allItems')
  return {
    props: { itens: data },
  }
}