import Head from 'next/head'
import { GetStaticProps } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { Col, Container, Row } from 'react-grid-system'
import IProductDTO from '@/interfaces/IProductDTO'
import CreateCategoryDTO from '@/interfaces/category/CreateCategory'
import { api } from '@/services/api'
import styles from '@/styles/Index.module.scss'
import Logo from "/public/Frame.png"

export const clickItem = async (idProduct: number): Promise<void> => {
  const { data } = await api.post<{ click: number }>('/clickCounter', { idProduct })
}
export default function Home({ itens, categories }: { itens: IProductDTO[], categories: CreateCategoryDTO[] }) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className={styles.header}>
          <h1 className={styles.restaurantName}>Restaurante do bem</h1>
        </header>
        <Container>
          <section>
            <div className={styles.research}>
              <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M8 15C11.866 15 15 11.866 15 8C15 4.13401 11.866 1 8 1C4.13401 1 1 4.13401 1 8C1 11.866 4.13401 15 8 15Z" stroke="#D0D4DD" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
                <path d="M12.95 12.95L17 17" stroke="#D0D4DD" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" />
              </svg>
              <input placeholder='Pesquise pelo item desejado...' />
            </div>
          </section>
          {itens?.map((item: IProductDTO) => (
            <Link key={item?.id} href={`/${item?.id}`} style={{ textDecoration: 'none', color: 'black' }}>
              <div onClick={() => clickItem(item?.id)} className={styles.productContainer}>
                <div className={styles.productDescription}>
                  <h3>{item?.name}</h3>
                  <h4>{item?.description}</h4>
                  <h2>R$ {item?.price}</h2>
                </div>
                <Image
                  className={styles.productImage}
                  alt="Image product"
                  src={Logo}
                />
              </div>
            </Link>
          ))}
        </Container>
      </main>
    </div>
  )
}

interface Response {
  itens: Array<any>;
  categories: any;
}

export const getStaticProps: GetStaticProps<Response> = async () => {
  const itemsResponse = await api.get('/Item/getItems')
  const categoriesResponse = await api.get('/category/getCategories')

  return {
    props: { itens: itemsResponse.data, categories: categoriesResponse.data },
  }
}