import Head from 'next/head'
import Image from 'next/image'
import { api } from '../service/api'
import styles from '../styles/Home.module.css'

export default function Home() {

  const clickItem = async (): Promise<void> => {
    const {data} = await api.get<{click: number}>('/clickCounter')
    console.log(data.click)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div onClick={clickItem}>
            <p>NOME</p>
            <p>DESCRIÇÃO</p>
            <p>PREÇO</p>
          </div>
        </div>
      </main>
    </>
  )
}
